type SanctumFloors {
  Id: string
  WorldArea: WorldAreas
  Name: ClientStrings
  Background: string
  BossIcon: string
  BossDescription: string
  RunEndedSummary: ClientStrings
}

type SanctumFodderLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type SanctumLifeScalingPerLevel {
  Level: i32
  MoreLife: i32
}

type SanctumRooms {
  Id: string
  Room: string
  RoomType: SanctumRoomTypes
  _: string
  Floor: SanctumFloors
  BossArea: WorldAreas
}

type SanctumRoomTypes {
  Id: string
  IsRewardRoom: bool
  _: bool
  StartSessionQuestFlag: SessionQuestFlags
  CompleteSessionQuestFlag: SessionQuestFlags
  _: i32
  _: bool
  Icon: string
  _: bool
  Description: string
  Names: [string]
  AchievementItems: [AchievementItems]
  DescriptionHardMode: string
  _: bool
}
