name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn --frozen-lockfile
    - run: yarn run tsc
    - run: yarn run generate
    - name: Upload schema
      uses: ncipollo/release-action@v1
      with:
        artifacts: "schema.min.json,schema.jsonl"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
